export const data = [
  {
    img: "https://mangageko.com/media/manga_covers/57448.jpg",
    title: "Mercenary Enrollment",
    rating: 4.5,
    rank: 1,
  },
  {
    img: "https://mangageko.com/media/manga_covers/420_uLWgqEt.jpg",
    title: "The Heavenly Docter",
    rating: 4.2,
    rank: 2,
  },
  {
    img: "https://mangageko.com/media/manga_covers/return-of-the-8th-class-magician.jpg",
    title: "Reincarnation of the Strongest",
    rating: 4.3,
    rank: 3,
  },
  {
    img: "https://mangageko.com/media/manga_covers/cover_12.jpg",
    title: "The Evil God",
    rating: 4.9,
    rank: 4,
  },
  {
    img: "https://mangageko.com/media/manga_covers/trickster.jpeg",
    title: "Trickster",
    rating: 4.0,
    rank: 5,
  },
  {
    img: "https://mangageko.com/media/manga_covers/xxlarge_F2NUb1S.jpg",
    title: "The Live",
    rating: 4.5,
    rank: 1,
  },
  {
    img: "https://mangageko.com/media/manga_covers/49842.jpg",
    title: "Trigger",
    rating: 4.2,
    rank: 2,
  },
  {
    img: "https://mangageko.com/media/manga_covers/cover_1_DrJkaWz.jpg",
    title: "Sword Sheath's Child",
    rating: 4.3,
    rank: 3,
  },
  {
    img: "https://mangageko.com/media/manga_covers/unnamed_SgIWf4Q.jpg",
    title: "The Boxer",
    rating: 4.9,
    rank: 4,
  },
  {
    img: "https://mangageko.com/media/manga_covers/k722631932_2.jpg",
    title: "Solo Levelling",
    rating: 4.0,
    rank: 5,
  },
  {
    img: "https://mangageko.com/media/manga_covers/%EC%99%80%EC%9D%B4%EB%9E%A9-%EC%95%84%ED%8A%B8-%ED%94%84%EB%A1%9C%EB%93%80%EC%8B%B1-%ED%8C%80-%EC%B1%84%EC%9A%A9-%EA%B3%B5%EA%B3%A0-01.jpg",
    title: "Study Group",
    rating: 4.5,
    rank: 1,
  },
  {
    img: "https://mangageko.com/media/manga_covers/%EC%9B%B9%ED%88%B0_%EC%86%8C%EC%9A%94%EC%9C%A0.jpg",
    title: "The Wanderer",
    rating: 4.9,
    rank: 4,
  },
  {
    img: "https://mangageko.com/media/manga_covers/cover_2_weWbhL4.jpg",
    title: "1 Second",
    rating: 4.2,
    rank: 2,
  },
  {
    img: "https://mangageko.com/media/manga_covers/48720.png",
    title: "How to Fight",
    rating: 4.3,
    rank: 3,
  },
];
export const genres = [
  "fantasy",
  "action",
  "adventure",
  "comedy",
  "mystery",
  "psychological",
  "magic",
  "martial arts",
  "sports",
  "thriller",
  "romance",
  "tragedy",
  "supernatural",
  "Sci-fi",
];
export const browseNovels = [
  {
    img: "https://mangageko.com/media/manga_covers/cover_1_DrJkaWz.jpg",
    title: "Sword Sheath's Child",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 1,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/420_uLWgqEt.jpg",
    title: "The Beginning After the End",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 2,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/return-of-the-8th-class-magician.jpg",
    title: "Reincarnation of the Strongest Swordsman",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 2,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/cover_12.jpg",
    title: "The Evil God",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 4,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/trickster.jpeg",
    title: "Trickster",
    rating: 4.0,
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rank: 5,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/3b1124c5-f877-4e3b-9e24-0ad3932c7922_z.jpg",
    title: "The Live",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 6,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/49842.jpg",
    title: "Trigger",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 7,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/unnamed_SgIWf4Q.jpg",
    title: "The Boxer",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 8,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/k722631932_2.jpg",
    title: "Solo Levelling",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 9,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/%EC%99%80%EC%9D%B4%EB%9E%A9-%EC%95%84%ED%8A%B8-%ED%94%84%EB%A1%9C%EB%93%80%EC%8B%B1-%ED%8C%80-%EC%B1%84%EC%9A%A9-%EA%B3%B5%EA%B3%A0-01.jpg",
    title: "Study Group",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 10,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/%EC%9B%B9%ED%88%B0_%EC%86%8C%EC%9A%94%EC%9C%A0.jpg",
    title: "The Wanderer",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 11,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/61000.jpg",
    title: "1 Second",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 12,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
  {
    img: "https://mangageko.com/media/manga_covers/48720.png",
    title: "How to Fight",
    author: "Kim Yohan",
    chapters: "145",
    status: "Completed",
    rating: 4.5,
    rank: 13,
    bookmarked: 208,
    desc: "u Ijin was the sole survivor of a plane crash when he was little. After becoming a mercenary to survive for 10 years, he returns to his family in his hometown.",
  },
];
export const currentProgress = [
  {
    name: "Reincarnation of the Strongest",
    img: "https://static.lightnovelpub.com/bookcover/158x210/00016-reincarnation-of-the-strongest-sword-god-novel.jpg",
    progress: 0.71,
    rating: 4.7,
  },
  {
    name: "Count of Monte Christo",
    img: "https://static.lightnovelpub.com/bookcover/158x210/00548-the-beginning-after-the-end.jpg",
    progress: 0.1,
    rating: 4.4,
  },
  {
    name: "Mercenary Enrollment",
    img: "https://mangageko.com/media/manga_covers/57448.jpg",
    progress: 0.23,
    rating: 4.9,
  },
  {
    name: "Eleceed",
    img: "https://static.lightnovelpub.com/bookcover/158x210/00091-super-god-gene-novel.jpg",
    progress: 0.89,
    rating: 4.1,
  },
  {
    name: "Guilty Trigger",
    img: "https://static.lightnovelpub.com/bookcover/158x210/00045-trash-count-novel.jpg",
    progress: 0.44,
    rating: 4.6,
  },
  {
    name: "The Boxer",
    img: "https://static.lightnovelpub.com/bookcover/158x210/00016-reincarnation-of-the-strongest-sword-god-novel.jpg",
    progress: 0.75,
    rating: 4.3,
  },
];
export const favGenre = {
  labels: [
    "action",
    "adventure",
    "psychological",
    "horror",
    "comedy",
    "others",
  ],
  datasets: [
    {
      data: [200, 300, 150, 250, 130, 50],
      backgroundColor: [
        "rgb(117, 255, 154)",
        "rgb(255, 138, 177)",
        "rgb(255, 220, 133",
        "rgb(255, 88, 77)",
        "rgb(138, 165, 255)",
        "rgb(255, 125, 125)",
      ],
      borderWidth: 0,
    },
  ],
};
export const following = [
  "James Cameron",
  "Mahatma Gandhi",
  "Ellie Williams",
  "Paul Rudd",
  "Satoshi",
  "John Morrison",
  "Kim Jong Un",
  "Joe Biden",
  "James Cameron",
  "Mahatma Gandhi",
  "Ellie Williams",
  "Paul Rudd",
  "Beuterik",
  "Drake",
  "Kim Jong Un",
  "Joe Biden",
  "James Cameron",
  "Mahatma Gandhi",
  "Ellie Williams",
  "Paul Rudd",
  "John Cena",
  "K Nakamoto",
  "Kim Jong Un",
  "Joe Biden",
];
export const categoryList = [
  "action",
  "adult",
  "adventure",
  "aliens",
  "animals",
  "comedy",
  "cooking",
  "crime",
  "delinquents",
  "demons",
  "drama",
  "fantasy",
  "game",
  "ghosts",
  "historical",
  "horror",
  "isekai",
  "kids",
  "mafia",
  "magic",
  "martial arts",
  "mature",
  "mecha",
  "medical",
  "military",
  "music",
  "mystery",
  "ninja",
  "one shot",
  "philosophical",
  "post apocalyptic",
  "psychological",
  "reincarnation",
  "romance",
  "samurai",
  "school life",
  "sci fi",
  "seinen",
  "Shoujo",
  "Shounen",
  "slice of life",
  "space",
  "sports",
  "super power",
  "superhero",
  "supernatural",
  "survival",
  "suspense",
  "thriller",
  "time travel",
  "tragedy",
  "vampire",
];
